# Generated by Django 3.0.5 on 2020-05-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='total_sum',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Сумма'),
        ),
    ]
